export const CREATE_NOTE_INIT = 'CREATE_NOTE_INIT';
export const CREATE_NOTE_START = 'CREATE_NOTE_START';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';

export const UPDATE_NOTE_INIT = 'UPDATE_NOTE_INIT';
export const UPDATE_NOTE_START = 'UPDATE_NOTE_START';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
